### ISSUE TITLE
export MathboxAPIContext?

### ISSUE THREAD

**Issue by sritchie** [ChristopherChudzicki/mathbox-react#239]
I'm testing out the idea of components that can configure Threestrap plugins; to get access to those, I'd like to use `useContext` to get the existing selection and access `renderer`, `controls` etc from there.

@ChristopherChudzicki, what do you think of exposing `MathboxAPIContext` from `mathbox-react`?

**Comment by ChristopherChudzicki** [comment]
MathboxAPIContext:
- can be used as `<MathboxAPIContext.Provider value={...} />` to set the context value
- can be used in `useContext(MathboxAPIContext)` to consume the context value

I don't think that library consumers should ever need to set the context value... that should be done automatically when using components (Group, Mathbox, hypothetical Root, etc). *I could well be wrong, and if there is a need to set the context value, let me know*.

So I would rather expose something like
```ts
export const useMathbox = () => {
  return useContext(MathboxAPIContext)
}
```
That seems like a reasonable thing to do to me.

**Comment by sritchie** [comment]
Yes, that's much better! I don't have any need to set, just use, so this is better for sure.

**Comment by ChristopherChudzicki** [comment]
Completed by #242

**Comment by ChristopherChudzicki** [comment]
@sritchie This should be available now:
```js
import { useMathbox } from "mathbox-react"
```
Although I suppose there's still confusion around the casing...
